graph TB
    subgraph "Internet"
        DNS[DigitalOcean DNS<br/>stagiaire1.example.com]
        User[Utilisateur]
    end
    
    subgraph "Scaleway Cloud"
        subgraph "Node 1 - Master (DEV1-M)"
            N1_PUB[IP Publique]
            N1_PRIV[IP Privée Scaleway]
            N1_VPN[IP VPN WireGuard<br/>10.0.1.1]
            N1_K8S[Kubernetes Master<br/>+ etcd]
            N1_UFW[UFW Firewall]
            N1_CILIUM[Cilium CNI]
        end
        
        subgraph "Node 2 - Worker (DEV1-M)"
            N2_PUB[IP Publique]
            N2_PRIV[IP Privée Scaleway]
            N2_VPN[IP VPN WireGuard<br/>10.0.1.2]
            N2_K8S[Kubernetes Worker<br/>+ etcd]
            N2_UFW[UFW Firewall]
            N2_CILIUM[Cilium CNI]
        end
        
        subgraph "Node 3 - Worker (DEV1-M)"
            N3_PUB[IP Publique]
            N3_PRIV[IP Privée Scaleway]
            N3_VPN[IP VPN WireGuard<br/>10.0.1.3]
            N3_K8S[Kubernetes Worker<br/>+ etcd]
            N3_UFW[UFW Firewall]
            N3_CILIUM[Cilium CNI]
        end
    end
    
    subgraph "Réseaux"
        VPN_NET[Réseau VPN<br/>10.0.1.0/24]
        K8S_NET[Réseau Kubernetes<br/>10.96.0.0/16]
    end
    
    %% Connexions DNS
    DNS --> N1_PUB
    DNS --> N2_PUB
    DNS --> N3_PUB
    
    %% Connexions utilisateur
    User --> DNS
    User -.->|SSH| N1_PUB
    User -.->|kubectl| N1_PUB
    
    %% Connexions VPN
    N1_VPN <--> VPN_NET
    N2_VPN <--> VPN_NET
    N3_VPN <--> VPN_NET
    VPN_NET <--> N1_VPN
    VPN_NET <--> N2_VPN
    VPN_NET <--> N3_VPN
    
    %% Connexions Kubernetes
    N1_CILIUM <--> K8S_NET
    N2_CILIUM <--> K8S_NET
    N3_CILIUM <--> K8S_NET
    
    %% Relations internes
    N1_PUB --- N1_PRIV
    N1_PRIV --- N1_VPN
    N1_VPN --- N1_K8S
    N1_K8S --- N1_CILIUM
    N1_UFW --- N1_PUB
    
    N2_PUB --- N2_PRIV
    N2_PRIV --- N2_VPN
    N2_VPN --- N2_K8S
    N2_K8S --- N2_CILIUM
    N2_UFW --- N2_PUB
    
    N3_PUB --- N3_PRIV
    N3_PRIV --- N3_VPN
    N3_VPN --- N3_K8S
    N3_K8S --- N3_CILIUM
    N3_UFW --- N3_PUB
    
    style VPN_NET fill:#e1f5e1
    style K8S_NET fill:#e1e5f5
    style N1_K8S fill:#ffd4d4
    style N2_K8S fill:#d4e8ff
    style N3_K8S fill:#d4e8ff