# https://skryvets.com/blog/2019/05/15/kubernetes-kustomize-json-patches-6902/

- op: replace
  path: "/spec/tls/hosts/0"
  value: "dev.monsterstack.scalelaab.dopl.uk"

- op: replace
  path: "/spec/tls/secretName"
  value: "monsterstack-tls-dev"

- op: replace
  path: "/spec/rules/0/host"
  value: "dev.monsterstack.scalelaab.dopl.uk"