# https://skryvets.com/blog/2019/05/15/kubernetes-kustomize-json-patches-6902/
- op: replace
  path: "/spec/tls/hosts/0"
  value: "prod.monsterstack.scalelaab.dopl.uk"

- op: replace
  path: "/spec/tls/secretName"
  value: "monsterstack-tls-prod"

- op: replace
  path: "/spec/rules/0/host"
  value: "prod.monsterstack.scalelaab.dopl.uk"
