[metadata]
scan_date = "2025-07-08T19:45:49.186276"
profile = "default"
total_regions_scanned = 17
regions_scanned = [ "ap-south-1", "eu-north-1", "eu-west-3", "eu-west-2", "eu-west-1", "ap-northeast-3", "ap-northeast-2", "ap-northeast-1", "ca-central-1", "sa-east-1", "ap-southeast-1", "ap-southeast-2", "eu-central-1", "us-east-1", "us-east-2", "us-west-1", "us-west-2",]

[summary]
total_instances = 27

[summary.by_state]
running = 27

[summary.by_region]
ap-south-1 = 0
eu-north-1 = 0
eu-west-3 = 18
eu-west-2 = 7
eu-west-1 = 0
ap-northeast-3 = 0
ap-northeast-2 = 0
ap-northeast-1 = 0
ca-central-1 = 0
sa-east-1 = 0
ap-southeast-1 = 0
ap-southeast-2 = 0
eu-central-1 = 2
us-east-1 = 0
us-east-2 = 0
us-west-1 = 0
us-west-2 = 0

[regions.ap-south-1]
instance_count = 0

[regions.eu-north-1]
instance_count = 0

[regions.eu-west-3]
instance_count = 18
instance_ids = [ "i-0783260ea633c9bf0", "i-0b75b3a73ea69038c", "i-01defdde5e0dd25a7", "i-0f514cdfc684766d2", "i-0b9ad6dcef504bc11", "i-0a3a7954889071d95", "i-0e7d8b669e671c4e0", "i-08bd6fcd713482012", "i-04d4b2ab4d6b817fe", "i-08eeebb0885d88ee8", "i-0cf49d1ef2e1a5dd7", "i-0330263c4b61ca527", "i-07199ceedfbe0206b", "i-0569133fcad54b493", "i-014a7d6fdf35191db", "i-03d7459a430a89db1", "i-03e5217baa2cee92b", "i-03337992b41df974a",]

[regions.eu-west-2]
instance_count = 7
instance_ids = [ "i-0b9ff1f4ee5815cdc", "i-0d23432a4635c2db9", "i-04bf221f981ad558a", "i-0f2f76dd1c5cfd70e", "i-0df9b5a5e83fb4340", "i-01d984087387b0826", "i-0f409eece8de51448",]

[regions.eu-west-1]
instance_count = 0

[regions.ap-northeast-3]
instance_count = 0

[regions.ap-northeast-2]
instance_count = 0

[regions.ap-northeast-1]
instance_count = 0

[regions.ca-central-1]
instance_count = 0

[regions.sa-east-1]
instance_count = 0

[regions.ap-southeast-1]
instance_count = 0

[regions.ap-southeast-2]
instance_count = 0

[regions.eu-central-1]
instance_count = 2
instance_ids = [ "i-0fa80565c7f34f6f9", "i-02e60c1824ee0a560",]

[regions.us-east-1]
instance_count = 0

[regions.us-east-2]
instance_count = 0

[regions.us-west-1]
instance_count = 0

[regions.us-west-2]
instance_count = 0

[regions.ap-south-1.instances]

[regions.eu-north-1.instances]

[regions.eu-west-1.instances]

[regions.ap-northeast-3.instances]

[regions.ap-northeast-2.instances]

[regions.ap-northeast-1.instances]

[regions.ca-central-1.instances]

[regions.sa-east-1.instances]

[regions.ap-southeast-1.instances]

[regions.ap-southeast-2.instances]

[regions.us-east-1.instances]

[regions.us-east-2.instances]

[regions.us-west-1.instances]

[regions.us-west-2.instances]

[regions.eu-west-3.instances.i-0783260ea633c9bf0]
id = "i-0783260ea633c9bf0"
state = "running"
type = "t2.micro"
name = ""

[regions.eu-west-3.instances.i-0b75b3a73ea69038c]
id = "i-0b75b3a73ea69038c"
state = "running"
type = "t2.micro"
name = ""

[regions.eu-west-3.instances.i-01defdde5e0dd25a7]
id = "i-01defdde5e0dd25a7"
state = "running"
type = "t2.micro"
name = ""

[regions.eu-west-3.instances.i-0f514cdfc684766d2]
id = "i-0f514cdfc684766d2"
state = "running"
type = "t2.micro"
name = ""

[regions.eu-west-3.instances.i-0b9ad6dcef504bc11]
id = "i-0b9ad6dcef504bc11"
state = "running"
type = "t2.micro"
name = ""

[regions.eu-west-3.instances.i-0a3a7954889071d95]
id = "i-0a3a7954889071d95"
state = "running"
type = "t2.micro"
name = ""

[regions.eu-west-3.instances.i-0e7d8b669e671c4e0]
id = "i-0e7d8b669e671c4e0"
state = "running"
type = "t2.micro"
name = ""

[regions.eu-west-3.instances.i-08bd6fcd713482012]
id = "i-08bd6fcd713482012"
state = "running"
type = "t2.micro"
name = ""

[regions.eu-west-3.instances.i-04d4b2ab4d6b817fe]
id = "i-04d4b2ab4d6b817fe"
state = "running"
type = "t2.micro"
name = ""

[regions.eu-west-3.instances.i-08eeebb0885d88ee8]
id = "i-08eeebb0885d88ee8"
state = "running"
type = "t2.micro"
name = ""

[regions.eu-west-3.instances.i-0cf49d1ef2e1a5dd7]
id = "i-0cf49d1ef2e1a5dd7"
state = "running"
type = "t2.small"
name = ""

[regions.eu-west-3.instances.i-0330263c4b61ca527]
id = "i-0330263c4b61ca527"
state = "running"
type = "t2.small"
name = ""

[regions.eu-west-3.instances.i-07199ceedfbe0206b]
id = "i-07199ceedfbe0206b"
state = "running"
type = "t2.micro"
name = ""

[regions.eu-west-3.instances.i-0569133fcad54b493]
id = "i-0569133fcad54b493"
state = "running"
type = "t2.micro"
name = ""

[regions.eu-west-3.instances.i-014a7d6fdf35191db]
id = "i-014a7d6fdf35191db"
state = "running"
type = "t2.small"
name = ""

[regions.eu-west-3.instances.i-03d7459a430a89db1]
id = "i-03d7459a430a89db1"
state = "running"
type = "t2.micro"
name = ""

[regions.eu-west-3.instances.i-03e5217baa2cee92b]
id = "i-03e5217baa2cee92b"
state = "running"
type = "t2.micro"
name = ""

[regions.eu-west-3.instances.i-03337992b41df974a]
id = "i-03337992b41df974a"
state = "running"
type = "t2.micro"
name = ""

[regions.eu-west-2.instances.i-0b9ff1f4ee5815cdc]
id = "i-0b9ff1f4ee5815cdc"
state = "running"
type = "t2.micro"
name = ""

[regions.eu-west-2.instances.i-0d23432a4635c2db9]
id = "i-0d23432a4635c2db9"
state = "running"
type = "t2.micro"
name = ""

[regions.eu-west-2.instances.i-04bf221f981ad558a]
id = "i-04bf221f981ad558a"
state = "running"
type = "t2.small"
name = ""

[regions.eu-west-2.instances.i-0f2f76dd1c5cfd70e]
id = "i-0f2f76dd1c5cfd70e"
state = "running"
type = "t2.small"
name = ""

[regions.eu-west-2.instances.i-0df9b5a5e83fb4340]
id = "i-0df9b5a5e83fb4340"
state = "running"
type = "t2.small"
name = ""

[regions.eu-west-2.instances.i-01d984087387b0826]
id = "i-01d984087387b0826"
state = "running"
type = "t2.small"
name = ""

[regions.eu-west-2.instances.i-0f409eece8de51448]
id = "i-0f409eece8de51448"
state = "running"
type = "t2.small"
name = ""

[regions.eu-central-1.instances.i-0fa80565c7f34f6f9]
id = "i-0fa80565c7f34f6f9"
state = "running"
type = "t2.micro"
name = ""

[regions.eu-central-1.instances.i-02e60c1824ee0a560]
id = "i-02e60c1824ee0a560"
state = "running"
type = "t2.micro"
name = ""
