apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-demo
  labels:
    app: rancher-demo
spec:
  selector:
    matchLabels:
      app: rancher-demo
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: rancher-demo
    spec:
      containers:
      - image: monachus/rancher-demo
        name: rancher-demo
        ports:
        - containerPort: 8080
          name: demo-http