apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- frontend.yaml
- imagebackend.yaml
- redis.yaml
- redis-data-pvc.yaml
- monsterstack-ingress.yaml

configMapGenerator:
- name: frontend-config
  literals:
  - CONTEXT=PROD
  - IMAGEBACKEND_DOMAIN=imagebackend
  - REDIS_DOMAIN=redis