# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terraform-state-<YOUR-BUCKET-NAME>"
    dynamodb_table = "terraform-state-lock"
    encrypt        = true
    key            = "tp-fil-rouge-../dev/terraform.tfstate"
    profile        = "default"
    region         = "eu-west-3"
    use_lockfile   = true
  }
}
